#ifndef OFFSETS_H
#define OFFSETS_H

#define OFFSET_PLAYER1_NAME 0x55C8
#define OFFSET_PLAYER1_WALLET 0x6E58
#define OFFSET_PLAYER1_ABD 0x0
#define OFFSET_PLAYER1_POCKETS 0x6BD0

#endif // OFFSETS_H

